version: '3.8'

services:
  db:
    image: postgres:16
    container_name: rema_container
    environment:
      POSTGRES_DB: rema_db
      POSTGRES_USER: Rema
      POSTGRES_PASSWORD: 11fd24errt5$
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: