"""Change field updated_at

Revision ID: 29d4717c0da9
Revises: 10b5f2fe0d4e
Create Date: 2024-09-09 22:41:38.465663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d4717c0da9'
down_revision: Union[str, None] = '10b5f2fe0d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
